Feature/#74 product detail markup
woowa-techcamp-2021/store-3 pull request #108
Opened 2021-08-22 09:01 UTC by SecretJuJu

## :bookmark_tabs: #74 ProductDetail 컴포넌트의 상단에 표시되는 ProductDetailInfo 컴포넌트 입니다

## :heavy_check_mark: 셀프 체크리스트
> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message가 발생하지 않았나요?
- [ ] Coding Convention을 준수했나요?
- [ ] `npm run lint`나 `yarn lint`를 실행하였나요?
- [ ] storybook 을 이용해서 UI를 확인할 수 있나요?

## 소요 시간
> 이슈를 해결하며 사용된 시간

- 7시간

## :speech_balloon: 작업 내용
> 구현 내용 및 작업 했던 내역

* ProductDetailInfo 컴포넌트 작성
* ProductDetailContainer 컴포넌트 작성
* ProductDetailInfo 컴포넌트를 storybook을 이용하여 UI를 확인할 수 있게함

## :construction: PR 특이 사항
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 현재 API를 사용하지 않고 container, stroybook 모두 MockAPI 을 이용하여 데이터를 불러오고 있습니다.
- 간단하게 버튼 클릭과 레이아웃만 잡아둔 상태여서 여기에 API를 사용하는 커스텀 훅을 연결하는 작업이 필요합니다.
- Font awesome 을 사용해서 increase/decrease 와 같은 아이콘을 꾸미는게 어떤지 논의가 필요합니다.
- 테스트코드를 작성해야합니다.

(작업 내역 확인하기 편하도록 이미지 첨부)

<img width="1792" alt="스크린샷 2021-08-22 오후 6 00 04" src="https://user-images.githubusercontent.com/47034129/130349077-88ccbcbb-8f53-4cb6-b3b9-d75f76a7283c.png">

2021-08-22 17:11 UTC, chaeeun037 requested changes

2021-08-22 17:11 UTC, chaeeun037 commented on client/src/App.tsx
> +      <ProductDetailContainer />
앗 아앗.. 개발할 때 수정하고 잘못 커밋하신거죠? 수정해야할 것 같네요 ㅎㅎ

2021-08-22 17:31 UTC, hwookim requested changes
고생하셨습니다! 👍🏼  👍🏼 
확실히 슬슬 태그 구조가 복잡해지는군요...

좀 많은 리뷰를 달았습니다...😅
개인적인 의견도 다수 있으니, 승보님의 생각을 들려주시면 감사할 것 같아요 👍🏼 
적용 여부는 승보님의 선택에 맡기고 논의할 내용들에 대해 논의하고 나면 Approve 하겠습니당.

리뷰 외에 전체적으로 느끼는 것도 몇자 적어볼게요.

우선 eslint 한 번 돌려주세요!
error가 나는 부분도 있습니다 😢

컴포넌트 내부에 함수와 변수가 생기면서, 리렌더링 될 때마다 해당 변수/함수를 모두 재생성하지 않을까 싶습니다.
`useCallback`과 `useMemo`를 적절히 사용해야할 것 같습니다.
정말 필요한 함수/변수인지도 한 번 생각해보면 좋을 것 같고요. ☺️

setState의 거처에 관해서는 논의가 좀 필요할 것 같기도 하네요.
알려진 Container-Presentation 패턴은 모든 state를 Container에서 관리하는 게 맞겠지만...
저희는 모든 컴포넌트를 나누지 않고 큰 컴포넌트 단위로 컨테이너를 갖기 때문에
일부는 확실히 하위 Presentational 컴포넌트에서 가져야할 것 같아요.
뭐가 맞는진... 저도 잘 모르겠군요 😥

마지막으로, 전체적인 통일성 한 번만 봐주시면 좋을 것 같아요~
네이밍이라던지, 구조라던지요 ㅎㅎ

정말로 고생하셨습니다! 내일 뵈어요!

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +            </IDCreaseButtonWrapper>
이 친구들은 왜 prefix로 `I`를 갖고 있나요? 👀

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +  };
```suggestion
  const countBtnClickHandler = (add: number) => () => {
    const changedAmount = amount + add > 0 ? amount + add : 1;
    setAmount(changedAmount);
  };
```

이런 방식으로도 표현해볼 수 있을 것 같아요. 😄
만약 사용하신다면 네이밍은 바꾸는 걸로 😅

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/BuyButton.tsx
> +  return <ButtonWrapper onClick={onBtnClick}>바로 구매</ButtonWrapper>;
`Wrapper`라고 보기엔 그냥 버튼이 아닐까 싶기도 합니다 🤔

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/Buttons.tsx
> +      <BuyButton onBtnClick={onBuyBtnClick} />
각 버튼의 코드가 너무 짧아서, 컴포넌트로 나눌 필요가 있을까 싶기도 하네요 🤔

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOption.tsx
> +  const OptionDropdownRef = useRef<HTMLDivElement>() as React.MutableRefObject<HTMLInputElement>;
useRef의 generic은 Div고 형변환은 Input인 이유가 있을까요?
initValue를 넣는다면 형변환이 없어도 실행에는 문제가 없던데, 어떤 이유로 형변환을 하셨는지 궁금합니당.

++ 변수인데 대문자로 시작하는군요! 👀

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOption.tsx
> +  };
style보단 styled-components의 props를 이용해도 좋을 것 같아요.

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +      <ButtonIcon src="/icons/wishIcon.png" alt="관심상품 등록 아이콘" />
색상 변경이 가능할지 좀 걱정이네요 🤔

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOption.tsx
> +const ProductOption = (props: IProductOptionProps) => {
`ProductOption`보단 `ProductOptionSelector` 정도가 맞지 않으려나 싶습니다 ☺️

2021-08-22 17:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +        <DetailContainer>
Detail보단 그냥 Info 정도 아닐까 싶기도 합니당 ㅎㅎ

2021-08-22 17:37 UTC, SecretJuJu commented on client/src/App.tsx
> +      <ProductDetailContainer />
아앗 넵 수정 해 놓겠습니다

2021-08-22 17:38 UTC, SecretJuJu commented on client/src/App.tsx
> +      <ProductDetailContainer />
네네 그런 것 같습니다 ㅎㅎ 돌려놓겠습니다

2021-08-22 17:40 UTC, SecretJuJu commented
현우님 많은 코멘트 감사합니다!
모든 코멘트 꼼꼼하게 읽은 후 반영하겠습니다!

2021-08-22 17:55 UTC, hwookim commented
너무 많기도 해서... 😥
사실 작동상의 문제는 없으니 머지 후에 천천히 적용해도 될 것들이 많습니다!!
저는 이만 자러 총총,,,

2021-08-22 19:04 UTC, eun-seong reviewed
너무 고생하셨습니다! React도 공부하시느라고 힘드셨을텐데 😭
이미 저와 동일한 의견의 리뷰가 몇 개 있어서, 덧붙일 것만 조금 적었습니다!

추가적으로 PR하기 전 마지막에 lint를 돌려주시면 좋을 것 같아요:) 수고하셨씁니당

2021-08-23 02:29 UTC, SecretJuJu commented on client/src/containers/ProductDetailContainer.tsx
> +const ProductDetailContainer = (): JSX.Element => {
넵! ㅜㅜ

2021-08-23 02:48 UTC, SecretJuJu commented on client/src/components/ProductDetail/index.tsx
> +    </>
ProductDetail 컴포넌트안에 ProductDetailInfo, ProductInfoTab, ProductDetailImages, DeliveryInformation 등으로 구성되어있도록 구상을 했는데 지금보니까 ProductDetail 컴포넌트가 너무 커지는거 같네요..
하나하나 나누는게 좋을까요?

2021-08-23 02:51 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOption.tsx
> +  const OptionDropdownRef = useRef<HTMLDivElement>() as React.MutableRefObject<HTMLInputElement>;
엇 이건 아무래도 찾은 자료에서 복붙하면서 신경을 못쓴 부분같아요.. 해결하겠습니다!

2021-08-23 03:02 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +    <>
wrapper로 감싸기 전의 잔재인것같군요 처리했습니다!

2021-08-23 03:05 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +        <DetailContainer>
흠.. 그렇군요 :)

2021-08-23 03:13 UTC, SecretJuJu commented on client/mocks/productDetail.ts
> +import { IProductData, IProductOption } from '@/interfaces/productDetail.interface';
넵!

2021-08-23 06:44 UTC, SecretJuJu commented on client/public/reset.css
> +}
Number 타입 input에 increase, decrease 버튼을 제거하는건데 이 기능을 사용할 일이 없을것같아서 일단 넣어두었습니다!

혹시모르니 빼는게 나을까요?

2021-08-23 06:57 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +  setAmount: Function;
`Function` 타입 린트에서 걸리지않나요? 문제없었나요?

2021-08-23 06:57 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +    }
제가 아는 hop은 맥주 향미료밖에 없는데! 의미가 궁금하네요

2021-08-23 07:08 UTC, chaeeun037 commented on client/src/containers/ProductDetailContainer.tsx
> +  const [amount, setAmount] = useState<number>(1);
처음에는 presenter의 이름이 가진 역할때문에 다음 코드가 presentation에 들어가는것이 맞을까? 의아했는데
```javascript
  const onClick = () => {
    orderItem(amount);
  }
```
생각하다보니 아무래도 presentation과 container 관계가 1:1이다보니 현우님께서 말씀하신 부분 굉장히 좋은것 같네요. :)

2021-08-23 07:09 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/Buttons.tsx
> +      <BuyButton onBtnClick={onBuyBtnClick} />
흠.. 그렇군요..

그럼일단 한 코드에 합쳐놓은뒤에 common 적인 button이 생기면 그때 함 바꿔보는식으로 해보곘습니다 :)

2021-08-23 07:13 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +            </IDCreaseButtonWrapper>
맞습니다.. ㅎㅎ

2021-08-23 07:18 UTC, chaeeun037 commented on client/src/components/ProductDetail/index.tsx
> +    </>
팀 회의를 통해 논의한대로 이렇게 세가지로 나누게 되었네요 :)
- 상품 정보 및 콘솔(맨 위의 컴포넌트)
- 상품 상세 이미지
- 상품 필수 정보

2021-08-23 07:19 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-08-23 07:23 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/Buttons.tsx
> +      <BuyButton onBtnClick={onBuyBtnClick} />
아토믹한 느낌이 드는군요 :) 
컴포넌트로 쪼개서 코드가 간결해질수록 구조는 복잡해지는건 어쩔수 없네요 ㅠㅠ

2021-08-23 07:25 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +    // dropdown 을 위한 이벤트 위임
이벤트 위임 적용하셨군요 :) 넘 좋습니다!!

2021-08-23 07:25 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +    }
Router 장비의 next hop 이란 단어를 생각하고 클릭하고 증감하는 Amount 의 범위를 나타내려고했는데 제가 생각을 이상하게했나보군요!
increaseNumber 로 바꾸겠습니다

2021-08-23 07:37 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/TotalPrice.tsx
> +    </TotalPriceWrapper>
태그 네이밍 관련해서 궁금한점이 생겼는데 팀원들의 의견이 궁금합니다.

승보님께서 작성한 태그 이름 형식은 명시적인 부분에서 좋지만, 코드를 읽는 입장에서 한눈에 들어오지 않는 느낌이 들어서요.

컴포넌트를 나누어놨는데 태그 이름에 컴포넌트 이름을 한번 더 쓸 필요가 있는지에대해 의아해서 저는 다음과 같은 형식으로 개발했습니다.
```tsx
    <Wrapper>
      <Label>총 합계금액</Label>
      <TotalPrice>{totalPrice.toLocaleString()}원</TotalPrice>
    </Wrapper>
```

이 때, 페이지에서 다른 컴포넌트들과 함께 렌더링했을 때 문제가 발생하게 될까요?

문제가 있다면 제가 수정을 해야할것 같아서요! :)

2021-08-23 07:41 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +      <ButtonIcon src="/icons/wishIcon.png" alt="관심상품 등록 아이콘" />
현재 상태에서는 색이 칠해진 이미지를 구해오는 수밖에 없겠네요...

그 외에도 두 가지 방법이 있을것 같습니다.

**1. font-icon 사용하기**
- color 변경을 통해 쉽게 해결할 수 있습니다 :)
- https://fonts.google.com/icons
- https://fontawesome.com/v5.15/icons?d=gallery&p=1

**2. svg 사용하기**
- 아주 좋은 css filter generator가 있습니다 :) 
- https://codepen.io/sosuke/pen/Pjoqqp

2021-08-23 07:45 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +  height: 3.5rem;
승보님은 rem 단위를 많이 사용하시는데, 실제 클론 대상 홈페이지에서 px단위로 수치를 가져올 수 있음에도 불구하고 rem을 사용하시는 이유가 궁금합니다!

눈대중으로 수치를 변경하면서 진행하면 시간이 더 걸리고 귀찮을것 같아서요.

2021-08-23 07:47 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +}
저는 로직 관련된 코드보다 style을 먼저 작성해왔습니다 :)
`styled component`를 먼저 작성하는쪽에 한표 던집니다~

2021-08-23 07:49 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +        <Thumbnail src={thumbnail} alt={title + ' 상품 이미지'} />
다음과 같이 작성할 수도 있겠네요. :)
```tsx
<Thumbnail src={thumbnail} alt={`${title} 상품 이미지`} />
```

2021-08-23 07:51 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +  height: 3.5rem;
은성님 코드에서 rem을 많이 사용하고 있는거 같아서 따라 해 보았어요!
음 이건 같이 정하는게 좋을 것 같네요.. 노션에 적어두겠습니다!

2021-08-23 07:52 UTC, chaeeun037 commented on client/src/components/ProductDetail/index.tsx
> +const ProductDetail = (props: IProductDetailProps) => {
네이밍이 어렵네요 ㅠㅠ

2021-08-23 07:53 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +        <Thumbnail src={thumbnail} alt={title + ' 상품 이미지'} />
오! 더 보기 좋네요

2021-08-23 07:56 UTC, chaeeun037 approved these changes
너무 고생 많으셨어요~ 정말 복잡한 부분을 구현하셨군요 ㅠㅠ
박수드립니다!! 짝짝짝~

2021-08-23 07:56 UTC, chaeeun037 commented on client/src/components/ProductDetail/index.tsx
> +      <ProductDetailInfo buttonControl={buttonControl} productData={productData} stateControl={stateControl} />
해당 ProductDetailInfo 컴포넌트 `width`가 UI상에 1200px로 지정되어있어 다음 코드를 추가해야할것 같네요.

```tsx
const ProductDetailInfo = styled.div`
    width: 1200px;
    margin: 0 auto;
`;
```

2021-08-23 07:58 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +  height: 3.5rem;
은성님이 구현하신 HeaderNav처럼 UI가 없는 부분에 대해서는 rem을 사용하는 것이 확실히 편하지만, 보고 만들 수 있는 UI가 있다면 px가 편리할 수 있다고 생각합니다 :)

2021-08-23 07:59 UTC, SecretJuJu commented on client/src/components/ProductDetail/index.tsx
> +    </>
:)

2021-08-23 08:00 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +const PriceData = styled.strong`
그런데 어느순간부터 strong이 볼드체가 되지 않는것 같은건 제 착각일까요?...
![스크린샷 2021-08-23 오후 5 00 27](https://user-images.githubusercontent.com/40158029/130411934-bc937e8d-ae81-4e58-923a-e409fa711096.png)

2021-08-23 08:02 UTC, SecretJuJu commented on client/src/components/ProductDetail/index.tsx
> +      <ProductDetailInfo buttonControl={buttonControl} productData={productData} stateControl={stateControl} />
ProductDetailInfo의 width를 바깥쪽에서 정할 수 있게 현재 ProductDetailInfo의 width 가 100%로 걸려있는 상황입니다!

2021-08-23 08:03 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +}
음.. 저는 Styled component 보다 interface 가 아래있으면 코드를짜면서 가까운거리에 인터페이스를 두고 짤 수 있으니까 그게 더 좋아보이네요 👍

2021-08-23 08:03 UTC, hwookim commented on client/src/components/ProductDetail/index.tsx
> +    </>
각각의 부분을 ProductDetail로 묶기 보다 세개의 컨테이너로 나누고, 해당 컨테이너들을 Page 컴포넌트에서 취합하는 방식은 어떨까요?
프레젠테이션 컴포넌트가 너무 크고 많이 나뉜다면 컨테이너로 따로 묶을 수 없나 생각해보는 것도 좋은 것 같아요. 👀

2021-08-23 08:05 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +  height: 3.5rem;
그런데 이런 단위도 통일을 해야하는걸까요? 급 궁금해지네요. 'ㅅ'

2021-08-23 08:07 UTC, hwookim commented on client/public/reset.css
> +}
만약 다른 곳에서 number type의 input을 쓰게 될 때, 여기 적용된 코드를 생각해내지 못한다면 크게 당혹스러울 수도 있을 것 같아요.
정말 모두에게 적용될 것이 아니라면 해당 컴포넌트에 기술하는 쪽이 맞다고 생각합니당

2021-08-23 08:07 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +  height: 3.5rem;
흠.... 고민이네요.. 'ㅅ'

2021-08-23 08:11 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/TotalPrice.tsx
> +    </TotalPriceWrapper>
저도 채은님의 예시처럼 작성하긴 했는데,
생각해보니 함께 헤더를 만들 때는 다 명시하는 쪽으로 작성했군요.. 🤔

의미만 확실하다면 생략할 수 있는 부분은 생략하는 것도 좋은 것 같습니다!
지금 보기에는 별다른 문제가 없을 것 같아요

2021-08-23 08:20 UTC, hwookim reviewed
ㅎㅎ... 바꾸시는 와중에 중간 리뷰 한 번 더 슬쩍 드려봅니당...ㅎㅎ 😅

2021-08-23 08:20 UTC, hwookim commented on client/src/App.tsx
> +
이 친구도 여기선 호출이 안되겠군요 👀

2021-08-23 08:20 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +    const checkIfClickedOutside = (e: any) => {
check만 하지 않고 끄는 역할까지 하는군요 👀 
`onClickOutside` 정도는 어떨까요?

2021-08-23 08:20 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +          </OptionItem>
이것도 `OptionDropdown`에 이벤트를 위임해 관리할 수 있을 것 같아요!

`id`값으로 관리해도 괜찮을까요? 어딘가에서 중복될 일은 없을까요?
`data-id`로 관리하는 편이 조금 더 안전할 것 같아요. 😄

2021-08-23 08:30 UTC, hwookim commented on client/src/components/ProductDetail/index.tsx
> +    </>
ProductDetail 로 모든 것을 묶기보다
ProductDetailContainer에서 각각의 프레젠터를 호출하는 건 어떨까요?

아.. 그러면 Container에 스타일이 들어가게 되나...🤔

2021-08-23 08:37 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +      <ButtonIcon src="/icons/wishIcon.png" alt="관심상품 등록 아이콘" />
좋아요 👍

2021-08-23 09:01 UTC, SecretJuJu commented on client/public/reset.css
> +}
음.. 그렇군요
알겠습니다! 👍

2021-08-23 09:01 UTC, eun-seong commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +    }
ㅋㅋ큐ㅠㅠ 라우터 합....

2021-08-23 09:11 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +  height: 3.5rem;
기본이 되는 px를 정해두고 rem으로 조절하는 게 반응형을 짜게 된다면 더 맞는 거 같긴 하네요.
하지만 저희는 웹만 고려하며 짜니... px로 하는 게 나으려나요..? 🤔

2021-08-23 12:52 UTC, SecretJuJu commented on client/src/interfaces/productDetail.interface.ts
> +export interface IProductData {
넵! 좋습니다

2021-08-23 12:55 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +          </OptionItem>
네 아마 item_option 에대한 id값으로 관리하면 서버에서 중복된 id를 가진 item_option을 줄 것 같진 않네요 ㅎㅎ

2021-08-23 13:01 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +    // dropdown 을 위한 이벤트 위임
:)

2021-08-23 13:02 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +    const checkIfClickedOutside = (e: any) => {
음... 좋습니다!

2021-08-23 13:05 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +          </OptionItem>
이벤트위임방식으로 변경했습니다 :)

2021-08-23 13:11 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/TotalPrice.tsx
> +    </TotalPriceWrapper>
<img width="738" alt="스크린샷 2021-08-23 오후 10 10 55" src="https://user-images.githubusercontent.com/40158029/130453004-87d3c602-780b-48ca-ad41-459bf70c5411.png">

2021-08-23 13:15 UTC, SecretJuJu commented on client/src/components/ProductDetail/index.tsx
> +    </>
음.. 아마 ProductDetailContainer에서 묶어주게될 것 가튼데 그러면 그것들을 묶으면서 스타일이 container에 들어갈 것 같네요

2021-08-23 13:21 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +          </OptionItem>
`id`에 대한 이야기는, 서버 문제가 아니라 HTML에서의 `id` 문제를 말씀드렸던 거예요 😅
한 페이지 내에서 `id`는 중복되어 사용하면 안되기 때문에, 동적인 값을 넣는 것은 UUID를 쓰지 않는 이상 지양하는 것이 맞다고 봅니다.
그 대체재로 `data-id` 등을 쓰는 것이고요 ☺️

구글링한 관련 [질문 글](https://www.codeit.kr/community/threads/3268) 하나 첨부합니당

2021-08-23 13:23 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +const PriceData = styled.strong`
저희는 `reset.css`의 영향일지도...?

2021-08-23 13:23 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +      <ButtonIcon src="/icons/wishIcon.png" alt="관심상품 등록 아이콘" />
ProductDetailInfo 에 아이콘 적용하기 이슈를 따로 만들면 어떨까요?

2021-08-23 13:28 UTC, SecretJuJu commented on client/stories/components/ProductDetail/ProductDetail.stories.tsx
> +const ProductDetailStory = ({ productData }: IProductDetailStoryProps) => {
이게 스토리북으로 테스트하는 컴포넌트의 범위를 너무 크게 잡은것 같아요
ProductDetailInfo 에서 클릭시 드롭다운 같은것을 보여주려 container에서 넣어주는 useState와 같은것들을 넣어주느라 container와 똑같은 수준의 코드가 나온 것 같습니다!

UI 만 보여주기위해 위 기능들을 제거하는게 좋을까요?

2021-08-23 13:41 UTC, SecretJuJu commented on client/src/components/ProductDetail/index.tsx
> +const ProductDetail = (props: IProductDetailProps) => {
ProductDetailInfo 컴포넌트를 을 ProductDetail 아래에 두었다가 아까 회의한대로 

- 상품 정보 및 콘솔(맨 위의 컴포넌트)
- 상품 상세 이미지
- 상품 필수 정보

으로나누면서 해당부분은 삭제가 되었습니다 :)

2021-08-23 13:46 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +  const { onBuyBtnClick, onCartBtnClick, onWishBtnClick } = buttonsHandler;
음.. 그렇군요 그렇다면 현재 다른곳에서도 사용하고있는 방법으로 props를 전달하는것이 좋겠군요

2021-08-23 13:48 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +            )}
적용하였습니다!

2021-08-23 13:48 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +    setAmount(changeToAmount);
좋아요. 적용했습니다!

2021-08-23 13:52 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/AmountPanel.tsx
> +  };
오 좋네요... 반영하였습니다 1

2021-08-23 13:54 UTC, hwookim commented on client/stories/components/ProductDetail/ProductDetail.stories.tsx
> +const ProductDetailStory = ({ productData }: IProductDetailStoryProps) => {
https://github.com/woowa-techcamp-2021/store-3/pull/108#discussion_r693492233
이 코멘트와 약간 연결되는 것 같아요.

UI에 해당 동작이 포함된다면 구조를 한 번 고민해야할 것 같습니다.
해당 state가 container에 있어야만 하는지, UI를 위한 state는 아닌지 말이에요.
만약 있어야만 한다면, 적어도 다른 state에 대한 onClick 이벤트들은 삭제할 수 있지 않을까 싶어요.

2021-08-23 14:02 UTC, hwookim commented on client/src/components/ProductDetail/index.tsx
> +    </>
Container에서 완전히 스타일을 적용하지 않는다면,
Container : Presenter = 1:1의 관계일 수 밖에 없을 것 같기도 하네요.

저는 배치를 위한 Wrapper 정도는 괜찮지 않나 싶기도 해서..
전통적인 컨테이너-프레젠테이션 패턴에는 점점 벗어나긴 하지만요 😅

2021-08-23 14:16 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +const PriceData = styled.strong`
캡쳐된 이미지는 배민문방구입니다! 저희 프로젝트에서는 안해봤네요 'ㅅ'

하지만 배민문방구에도 strong 관련 설정은 없네요 ㅠㅠ
![스크린샷 2021-08-23 오후 11 15 03](https://user-images.githubusercontent.com/40158029/130462704-6714d5d1-4c30-4723-8e82-150fdadf8a89.png)

2021-08-23 14:31 UTC, hwookim commented on client/src/components/ProductDetail/ProductDetailInfo/index.tsx
> +const PriceData = styled.strong`
이럴슈가!
전역으로 설정해도 computed에는 보여야하지 않나요??? 뭘까...신기...
css의 세계는 심오하군요...

2021-08-23 14:33 UTC, eun-seong commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +  height: 3.5rem;
그러게요..! 저는 거의 모든 단위를 rem으로 작성하는데 다른 분들 코드를 보면 px와 rem을 함께 사용하시더라구용
이 단위도 원래 아예 통일하나요...?

2021-08-23 14:44 UTC, SecretJuJu commented on client/src/components/ProductDetail/ProductDetailInfo/ProductOptionSelector.tsx
> +          </OptionItem>
앗 그렇군요! 일단 그래서 지금은 data-id를 사용하는거로 변경되어있습니다!
<img width="350" alt="스크린샷 2021-08-23 오후 11 44 04" src="https://user-images.githubusercontent.com/47034129/130467338-8e5efe1c-f3e3-4494-92af-29cbc051716e.png">

2021-08-23 14:54 UTC, hwookim approved these changes
정말..정말... 고생하셨습니다!!!!!!!!!!
승보님은 최고예요 ㅠㅠㅜㅠㅠㅠㅠ 👍🏼 👍🏼 👍🏼 👍🏼

2021-08-23 14:54 UTC, hwookim commented on client/src/components/ProductDetailInfo/index.tsx
> +const ProductDetailInfo = ({ productData, onBuyBtnClick, onCartBtnClick, onWishBtnClick }: IProductDetailInfoProps) => {
얘도 props로 할 수 있을 것 같기도.. ㅎㅎ 😅

2021-08-23 14:57 UTC, SecretJuJu commented on client/src/components/ProductDetailInfo/index.tsx
> +const ProductDetailInfo = ({ productData, onBuyBtnClick, onCartBtnClick, onWishBtnClick }: IProductDetailInfoProps) => {
엇 어떤거죠!?

2021-08-23 15:01 UTC, hwookim commented on client/src/components/ProductDetailInfo/index.tsx
> +const ProductDetailInfo = ({ productData, onBuyBtnClick, onCartBtnClick, onWishBtnClick }: IProductDetailInfoProps) => {
앗 다른 곳은 
```typescript
const Component = (props: IProps) => {
  const { a, b, c } = props;
  ...
}
```
의 형태라서 한 번 이야기 해봤슴당.. ㅎㅎ

2021-08-23 15:03 UTC, SecretJuJu commented on client/src/components/ProductDetailInfo/index.tsx
> +const ProductDetailInfo = ({ productData, onBuyBtnClick, onCartBtnClick, onWishBtnClick }: IProductDetailInfoProps) => {
아아 그렇군요! 통일 해 버리겠습니다

2021-08-23 17:18 UTC, chaeeun037 commented on client/src/components/ProductDetail/ProductDetailInfo/WishButton.tsx
> +  height: 3.5rem;
우린 디자이너가 없으니.. 그냥 이대로 가는것도 좋은것 같습니다! :)

2021-08-24 00:49 UTC, eun-seong approved these changes
너무 수고하셨어용 👍 👍 👍

2021-08-24 00:56 UTC, merged

2021-08-24 01:14 UTC, SecretJuJu commented on client/src/components/ProductDetail/index.tsx
> +      <ProductDetailInfo buttonControl={buttonControl} productData={productData} stateControl={stateControl} />
이곳이 어딘가요!