[Feature/#160 search api] 검색 api
woowa-techcamp-2021/store-3 pull request #162
Opened 2021-08-24 13:30 UTC by SecretJuJu

## :bookmark_tabs: #160 검색 ap

## :heavy_check_mark: 셀프 체크리스트
> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message가 발생하지 않았나요?
- [ ] Coding Convention을 준수했나요?
- [ ] `npm run lint`나 `yarn lint`를 실행하였나요?

## 소요 시간
> 이슈를 해결하며 사용된 시간

- 1시간

## :speech_balloon: 작업 내용
> 구현 내용 및 작업 했던 내역

* keyword 를 이용해 검색시 item 배열 리턴

## :construction: PR 특이 사항
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- (특이 사항 1)

(작업 내역 확인하기 편하도록 이미지 첨부)

2021-08-24 13:49 UTC, hwookim requested changes
자동 완성 PR에 들어갈 리뷰도 여기 몇 개 포함된 것 같기도 하네요...😅
고생하셨습니다 👍🏼 👍🏼

2021-08-24 13:49 UTC, hwookim commented on server/src/services/item.service.ts
> +  async _searchToElasticSearch(keyword: string) {
private를 의도한 네이밍이려나요?
typescript에는 접근제어자가 존재하니 네이밍으로 표현하기보단 명시해두는 편이 더 좋은 것 같아요!

return 타입도 명시하면 좋을 것 같군요 ☺️

2021-08-24 13:49 UTC, hwookim commented on server/src/services/item.service.ts
> +    });
```suggestion
    const items = result.hits.hits.map(({ _source }) => _source) as Item[];
```

이렇게도 표현할 수 있을 것네요.
```suggestion
    const items = result.hits.hits.map((hit) => hit._source as Item);
```
아님 이렇게도?

2021-08-24 13:49 UTC, hwookim commented on server/src/services/item.service.ts
> +    const result = await esClient.search({
```suggestion
    const result = await esClient.search<Item>({
```

이렇게 타입을 지정하면 아래에서 형변환을 진행하지 않아도 괜찮네요 👀

2021-08-24 13:49 UTC, hwookim commented on server/src/services/item.service.ts
> +    return result;
```suggestion
    return result.hits.hits;
```
사용처에서 보면 다 `result.hits.hits` 를 쓰던데, 아예 그렇게 내보내는 건 어떨까요?

2021-08-24 13:49 UTC, hwookim commented on server/src/services/item.service.ts
> +  }
```suggestion
  async autoCompleteKeyword(keyword: string): Promise<string[]> {
    const result = await this._searchToElasticSearch(keyword);
    return result.map((hit) => hit._source.title);
  }
```

`esClient.search<Item>`으로 제네릭 타입을 지정하고,
`result.hits.hits`를 반환했다면 아예 이렇게 줄일 수도 있겠어요 ☺️

2021-08-24 13:52 UTC, hwookim commented on server/src/services/item.service.ts
> +  async _searchToElasticSearch(keyword: string) {
타입을 명시하려면 `result.hits.hits`를 반환하긴 힘들 것 같긴 하네요. 🤔

2021-08-24 14:23 UTC, SecretJuJu commented on server/src/services/item.service.ts
> +    const result = await esClient.search({
오 그렇군요!

2021-08-24 14:24 UTC, SecretJuJu commented on server/src/services/item.service.ts
> +    return result;
hits가 아닌 따른것들을 혹시 사용할 수 있을까 해서 result 만 보냈는데 해당 방법도 좋아보이네요 :)

2021-08-24 14:26 UTC, SecretJuJu commented on server/src/services/item.service.ts
> +  }
좋습니다 👍

2021-08-24 16:12 UTC, chaeeun037 approved these changes
너무나도 깔끔한 코드!! 감격스럽네요~~~ :)
멋집니다 후후... 역시 승보님~~~~~

2021-08-24 16:12 UTC, chaeeun037 commented on server/src/services/item.service.ts
> +  async _searchToElasticSearch(keyword: string) {
저는 개인적으로 이러한 네이밍 선호하긴 합니다 :)

2021-08-25 00:27 UTC, hwookim approved these changes

2021-08-25 01:04 UTC, eun-seong approved these changes
수고하셨습니다 👍 👍 👍 👍

2021-08-25 01:08 UTC, merged