[Feature/#119 login page] login 페이지 개발
woowa-techcamp-2021/store-3 pull request #163
Opened 2021-08-24 15:41 UTC by chaeeun037

## :bookmark_tabs: #119 login 페이지 개발
resolve #119 

## :heavy_check_mark: 셀프 체크리스트
> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message가 발생하지 않았나요?
- [ ] Coding Convention을 준수했나요?
- [ ] `npm run lint`나 `yarn lint`를 실행하였나요?

## 소요 시간
> 이슈를 해결하며 사용된 시간

- 3시간

## :speech_balloon: 작업 내용
> 구현 내용 및 작업 했던 내역

[frontend]
- 테스트 계정 로그인
- 깃헙 계정 로그인
- HeaderTop 조건부 렌더링
- HeaderTop 로그인, 로그아웃 기능 추가

[backend]
- 테스트 계정 로그인 api 추가
- 깃헙 로그인시 가입되지 않은 사용자일 경우 가입 후 로그인

## :construction: PR 특이 사항
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 개발 중 github client_id, secret 제껄로 바꿔서 진행했습니다. 
- 프론트, 백 env 설정이 추가된 부분이 있습니다.
- 만들어져 있는 api를 지우지 않고 변경된 부분으로 수정 혹은 새로 개발하는 쪽으로 진행했습니다.
  - 이로 인해 기능이 겹치는 함수가 있고, 코드가 깔끔하지 않은 점 미리 말씀드립니다!
- 테스트 코드는 작성하지 않았습니다. 추후에 따로 이슈 생성하여 PR 올리겠습니다.

2021-08-24 16:45 UTC, SecretJuJu reviewed
리뷰를 진행하다가 이런부분도 하셨군요! 하는 부분이 있네요
저는 일단 코멘트 달고 내일 이어서 리뷰를 하도록 하겠습니다!

2021-08-24 16:45 UTC, SecretJuJu commented on client/.env.sample
> +OAUTH_GITHUB_CLIENT_SECRET=
👍

2021-08-24 16:45 UTC, SecretJuJu commented on client/src/App.tsx
> +      </AuthProvider>
라우터에 로그인 여부에따라 들어갈 수 있는 페이지를 뭔가가 미래에 필요해보이네요

2021-08-24 16:45 UTC, SecretJuJu commented on client/src/lib/AuthProvider.tsx
> +};
👍 👍

2021-08-24 16:45 UTC, SecretJuJu commented on server/src/services/auth.service.ts
>  }
오 Guest 유저

2021-08-25 01:47 UTC, SecretJuJu approved these changes
쿠키같은 코드를 보며 감탄했어요 ㅋㅋ
conflict 가 해결되어서 크로마틱으로 보면 좋겠네요!

2021-08-25 01:47 UTC, SecretJuJu commented on client/src/utils/cookie.ts
> +export default new Cookie();
getCookie, setCookie 등의 함수는 많이 봤어도 이렇게 클래스로 관리하니까 더 멋지네요 👍

2021-08-25 01:47 UTC, SecretJuJu commented on server/src/controllers/auth.controller.ts
> +    const accessToken = await authService.generateJWT(guest.id);
authorizeCallback 메서드처럼

비구조화로 할 수 있을 것 같아요!
```
const { id } = await authService.findGuestUser();
const accessToken = await authService.generateJWT(id);
```

2021-08-25 02:49 UTC, hwookim requested changes
로그인 버튼이 깔끔하고 좋네요 ㅎㅎ 👍🏼 👍🏼 

몇가지 리뷰 남겼으니 확인 부탁드려요~~
추가적으로 크로마틱 배포를 수동으로 한 번 해주시면 좋을 것 같아욥!

2021-08-25 02:49 UTC, hwookim commented on client/src/components/Header/index.tsx
> +  onLogoutButtonClick: () => void;
```suggestion
  onLogout: () => void;
```
외부에서는 `logout()` 함수만 넘겨주고 그것이 버튼을 클릭해서 발생하는 것인지 keypress 때문인지는 몰라도 될 것 같아요.
함수를 props로 할 때, 이벤트째로 넘겨주기보단 이벤트를 가공해서 넘겨주는 건 어떠신가요? ☺️

2021-08-25 02:49 UTC, hwookim commented on server/src/middlewares/error.middleware.ts
> +const errorMiddleware = (error: BaseError, req: Request, res: Response): void => {
next 없으면 작동 안하진 않나요? 🤔

2021-08-25 02:49 UTC, hwookim commented on client/src/lib/AuthProvider.tsx
> +  return <AuthContext.Provider value={{ isLoggedIn }}>{children}</AuthContext.Provider>;
중간에 쿠키가 소실되면 isLoggedIn이 풀려야하는데 그러진 않겠군요. 👀 

AuthProvider를 쓰기보단 그냥 utils에 구현해두신 걸 쓰는 건 어떨까요?
쿠키가 컨텍스트를 통해 전역 관리할 대상은 아니라는 생각이 들어요
테스트하기도 조금 힘들어 질 것 같구요. 😢

accessToken에만 접근하는 유틸성 함수로도 충분히 대체 가능할 것 같아요.

2021-08-25 02:49 UTC, hwookim commented on client/src/components/Login/index.tsx
> +  onGithubLoginClick: () => void;
```suggestion
  onGuestLogin: () => void;
  onGithubLogin: () => void;
```

이 친구들도 위의 리뷰와 같은 맥락으로,
어느 이벤트인지까지 상위 컴포넌트에서 알 필요 없을 것 같아요 ~ ☺️

2021-08-25 02:49 UTC, hwookim commented on client/src/lib/AuthProvider.tsx
> +import cookie from '@/utils/cookie';
전역 상태관리를 위해 AuthProvider가 쓰이고 있는데요.
만약 계속 쓰게 된다면 store 폴더로 구분하는 건 어떨까요?

lib는 router나 styled-components 같은 하나의 라이브러리를 표방한 친구들이 오면 좋을 것 같아요.

2021-08-25 02:49 UTC, hwookim commented on client/src/components/Header/HeaderTop.tsx
> +            <Link to="/login">로그인</Link>
a 태그에 대한 디자인이 필요할 것 같은데,
Link에서 일괄적으로 하는 게 나으려나요 🤔

2021-08-25 03:33 UTC, eun-seong approved these changes
와아 너무 고생하셨서요!! 👍 👍 👍

2021-08-25 03:33 UTC, eun-seong commented on client/src/containers/HeaderContainer.tsx
> +    window.location.href = '/';
`router.pushState()` 사용할 수 있을 것 같아요!

2021-08-25 03:33 UTC, eun-seong commented on client/src/pages/LoginPage.tsx
> +    </>
<></>
\>< >< >< >< >< >,.<
\>..<

2021-08-25 03:33 UTC, eun-seong commented on client/src/utils/cookie.ts
> +export default new Cookie();
오오 👍 👍
이대로도 좋고 함수형으로 작성해도 좋을 것 같아용😆

2021-08-25 03:33 UTC, eun-seong commented on client/src/utils/path.ts
> +export const parsePath = (pathname: string): string => pathname.replace('/', '');
이건 언제 사용하는건가요??

2021-08-25 03:33 UTC, eun-seong commented on client/src/utils/path.ts
> +};
오.. Path 유틸 함수 모두 너무 멋져용👍

2021-08-25 03:33 UTC, eun-seong commented on client/src/lib/AuthProvider.tsx
> +};
2222222

2021-08-25 03:33 UTC, eun-seong commented on client/src/containers/HeaderContainer.tsx
> +    cookie.remove('accessToken');
와 근데 이렇게 쓰니까 진짜 편하긴 하네요ㅠㅠㅠ AuthProvider까지 합쳐지니 강력합니다...

2021-08-25 03:33 UTC, eun-seong commented on client/src/utils/cookie.ts
> +      cookieString = `${cookieString}; expires=${expiresDate.setDate(expiresDate.getDate() + expires)}`;
브라우저를 종료하면 쿠키도 함께 삭제되는데 의도하신 건가요??

2021-08-25 03:33 UTC, eun-seong commented on client/src/App.tsx
> +      </AuthProvider>
[이렇게](https://github.com/woowa-techcamp-2021/store-3/pull/163/files#diff-3920d51ed8314563471ac92d82b2bcca2e7c67cf4dfbc99bf5a964e016a94ea5R31) 사용할 수 있을 것 같습니다!

2021-08-25 03:36 UTC, eun-seong commented on client/src/components/Header/HeaderTop.tsx
> +            <Link to="/login">로그인</Link>
공통적인 부분은 Link에서 넣어줘도 좋을것같아요!
text-decoration이랑 color 정도??

2021-08-25 04:01 UTC, hwookim commented on client/src/components/Header/HeaderTop.tsx
> +          <HeaderTopMenuItem>장바구니</HeaderTopMenuItem>
비회원을 없앴기 때문에 그럴 것 같긴 하네요 🤔

2021-08-25 05:16 UTC, chaeeun037 commented on client/src/containers/HeaderContainer.tsx
> +    window.location.href = '/';
새로고침을 해야하기 때문에 이렇게 썼습니다 :)

2021-08-25 05:18 UTC, chaeeun037 commented on client/src/utils/path.ts
> +export const parsePath = (pathname: string): string => pathname.replace('/', '');
앗 다른데서 사용했던 코드 긁어오다보니 안쓰는것도 들어갔군요 ㅎㅎ~ 수정해야겠습니다

2021-08-25 05:19 UTC, chaeeun037 commented on client/src/components/Header/HeaderTop.tsx
> +          <HeaderTopMenuItem>장바구니</HeaderTopMenuItem>
추가 구현이 필요할것같아 PR에도 적었듯이
>일단 장바구니, 찜리스트 기능은 로그인한 사용자에 한해서 가능하게 했습니다.

일단은 이렇게 진행했습니다!

2021-08-25 05:20 UTC, chaeeun037 commented on client/src/components/Header/index.tsx
> +  onLogoutButtonClick: () => void;
깔끔하고 괜찮은거같네요! :)

2021-08-25 05:21 UTC, chaeeun037 commented on client/src/components/Login/index.tsx
> +  onGithubLoginClick: () => void;
그런 방법이 있꾼요~~ 좋습니다!

2021-08-25 05:23 UTC, chaeeun037 commented on client/src/lib/AuthProvider.tsx
> +import cookie from '@/utils/cookie';
저는 아무래도 상관없습니다 :)

2021-08-25 05:27 UTC, chaeeun037 commented on client/src/lib/AuthProvider.tsx
> +  return <AuthContext.Provider value={{ isLoggedIn }}>{children}</AuthContext.Provider>;
처음에는 useState를 사용했었는데 중간에 쿠키 get, set해주는 경우가 명확하다고 생각해서 이렇게 진행했습니다..
전역으로 관리할 대상이 아니라고 생각하신 이유는 무엇이며 테스트는 하기가 왜 힘들어지는걸까요?
충분히 대체 가능하지만 편하게 사용하기 위해서 구현한것인데, 수정해야 할 정도로 심각하게 문제가 있는 코드인건지 제안을 하시는건지 헷갈립니다..

2021-08-25 05:32 UTC, chaeeun037 commented on client/src/utils/cookie.ts
> +      cookieString = `${cookieString}; expires=${expiresDate.setDate(expiresDate.getDate() + expires)}`;
guest 로그인일 경우 유지되는데 github 로그인에서 쿠키가 날아가네요... 이것은 버그입니다...!

2021-08-25 05:33 UTC, chaeeun037 commented on server/src/controllers/auth.controller.ts
> +    const accessToken = await authService.generateJWT(guest.id);
앗 감사합니다 ㅎㅎ왜저렇게 적었지!

2021-08-25 05:34 UTC, chaeeun037 commented on server/src/middlewares/error.middleware.ts
> +const errorMiddleware = (error: BaseError, req: Request, res: Response): void => {
lint 돌려보니 이곳에서 오류나길래 지웠네요.... 저는 error middleware 밑에 next를 항상 적었는데 사용하지 않아서 에러가 나네요.
next()를 적거나 인자에서도 지우거나 둘중 하나를 선택해야 하는걸까요

2021-08-25 05:59 UTC, hwookim commented on client/src/lib/AuthProvider.tsx
> +  return <AuthContext.Provider value={{ isLoggedIn }}>{children}</AuthContext.Provider>;
권한 요청이 있을 때마다 cookie 검사를 해야할 것 같은데,
맨 처음에 한 번 받고 나서 계속 같은 isLoggedIn을 사용하게 되면 실제 쿠키와 동기화가 안맞을 수 있다는 생각이 들어요.

이런 이유에서 매번 요청하게 된다면 전역으로 관리하는 것보단 유틸성 함수로 쿠키값을 호출하는 편이 낫다고 생각했습니다.

테스트에 관련해서는,
useContext를 사용하고 있는 컴포넌트를 테스트하기 위해선 해당 부분에 대한 mocking이 필요해지기 때문이었어요.
useContext에 대한 mocking 보단, 직접 만든 유틸성 함수가 mocking하긴 더 쉬워 보이고요.

2021-08-25 06:11 UTC, chaeeun037 commented on client/src/lib/AuthProvider.tsx
> +  return <AuthContext.Provider value={{ isLoggedIn }}>{children}</AuthContext.Provider>;
오호 테스트관점에서는 분명히 아주 불편하군요... 이번에 테스트 진행을 안하다보니 고려를 못했습니다!
저 AuthContext에서는 UI 렌더링 사용 측면에서만 구현한것이라 api 요청에서는 사실 cookie.get을 사용할것 같습니다. 그럼 cookie.get을 사용한 로그인 체크 util을 만들어서 사용하는 쪽으로 수정해야겠군요!

충분한 설명 감사드립니다 :)

2021-08-25 06:46 UTC, chaeeun037 commented on client/src/utils/cookie.ts
> +      cookieString = `${cookieString}; expires=${expiresDate.setDate(expiresDate.getDate() + expires)}`;
버그 확인해보니 localhost가 아닌 127.0.0.1를 사용해야 문제가 없군요.
실제 배포때는 해당되지 않으니 문제 없을것으로 보입니다!

2021-08-25 07:06 UTC, hwookim approved these changes
정말 고생하셨습니다!!
동작 상 문제는 없으니 approve 하겠습니당 👍🏼 👍🏼 

몇가지 리뷰 남겼으니 답변해주시면 감사하겠습니다! ☺️

2021-08-25 07:06 UTC, hwookim commented on client/src/utils/path.ts
> +};
완전히 같은 함수 같은데 나눠진 이유가 따로 있을까요??

2021-08-25 09:00 UTC, chaeeun037 commented on client/src/utils/path.ts
> +};
buildQuerystring를 내부에서 사용하는 용도, 외부에서 import해서 사용하는 용도로 나누었습니다 :)
각각 독립적인 메소드인데 같은 파일에서 사용하게 된다면 의존성이 생길 것을 고려했었습니다.

2021-08-25 09:02 UTC, chaeeun037 commented on client/src/containers/LoginContainer.tsx
> +      cookie.set('accessToken', data);
저도 이 부분 처리가 조금 애매해서 고민하긴 했는데 어떤식으로 수정하면 좋을지 코드로 알려주실수 있나요? :)

2021-08-25 09:08 UTC, hwookim commented on client/src/utils/path.ts
> +};
같은 파일에서 사용하면 문제가 생기나요?? 👀

2021-08-25 09:19 UTC, merged