Feature/#21 insert wish
woowa-techcamp-2021/store-3 pull request #24
Opened 2021-08-12 09:12 UTC by eun-seong

## :bookmark_tabs: #21 wish `POST` API 작성
it closes #21 

## :heavy_check_mark: 셀프 체크리스트
> 최소 3명 이상의 assign을 받아야만 Merge 가능합니다.

- [x] Warning Message가 발생하지 않았나요?
- [x] Coding Convention을 준수했나요?
- [x] `npm run lint`나 `yarn lint`를 실행하였나요?
- [x] 사용자의 wish에 아이템이 추가되나요?

## 소요 시간
> 이슈를 해결하며 사용된 시간

- 1시간

## :speech_balloon: 작업 내용
> 구현 내용 및 작업 했던 내역

* wishList의 `POST` API 작성했습니다.

```json
// 응답 Body
{
    "data": {
        "wishId": 11
    },
    "message": "아이템이 정상적으로 찜되었습니다."
}
```

## :construction: PR 특이 사항
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- [참고](https://github.com/woowa-techcamp-2021/store-3/pull/22/files#diff-3e570d0dee0b820205eb6898db3989b0d58fccdcf8cdc64ccec2551fc01733f7R25-R29) 사용자가 이미 찜한 아이템을 다시 찜하는 요청이 들어왔을 경우 데이터 중복을 방지하기 위해 이렇게 작성하였습니다만...!   
    프론트 단에서 아이템 리스트를 보여줄 때 이미 찜하고 있다는 것을 구분해서 보여준다면 문제가 없을 것같은데, 그렇지 않은 경우에 이미 찜한 상품이라는 알림을 해주어야 하지 않나 싶습니다.   
    현재는 이미 찜한 상품이든 새롭게 찜한 상품이든 `wishId`를 함께 응답해주고 있어서 프론트에서 이 둘을 구분할 방법이 없습니다.

2021-08-12 11:25 UTC, hwookim requested changes
고생하셨슴당!
request, response의 네이밍 형식을 재고해보면 좋을 것 같아요! 😄

2021-08-12 11:26 UTC, eun-seong commented on server/src/services/wish.service.ts
> +    );
헉 그렇군요!! 감사합니다 👍

2021-08-12 11:28 UTC, eun-seong commented on server/src/controllers/wish.controller.ts
> +  itemId: number;
수정하겠습니다!

2021-08-12 11:28 UTC, eun-seong commented on server/src/controllers/wish.controller.ts
> +    res.status(200).json({ data: { wishId: result.id }, message: '아이템이 정상적으로 찜되었습니다.' });
수정하겠습니다!

2021-08-12 11:34 UTC, SecretJuJu commented on server/src/services/wish.service.ts
> +      wish ??
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
오 신기한거 알아갑니다 :)

2021-08-12 11:35 UTC, SecretJuJu commented on server/src/routers/wish.router.ts
> +wishRouter.post('/', wrapAsync(wishController.insertItemToWish));
getAll
와
insertItemToWish

두 네이밍 형식이 다른것같습니다. 이것도 정하면 좋을 것 같아요!

2021-08-12 11:39 UTC, eun-seong commented
`findOne` 메소드를 `findOrCreate` 메소드로 변경하면서 응답도 변경되었습니다.

> 상품 찜
```json
{
    "data": {
        "wish_id": 13
    },
    "message": "아이템이 정상적으로 찜되었습니다."
}
```

> 중복으로 찜할 경우
```json
{
    "data": {
        "wish_id": 12
    },
    "message": "이미 찜한 상품입니다."
}
```

2021-08-12 11:41 UTC, eun-seong commented on server/src/routers/wish.router.ts
> +wishRouter.post('/', wrapAsync(wishController.insertItemToWish));
`insertItem`으로 하려고 했으나..

그럼 아이템 자체를 추가하는 건가? 하는 생각이 들어 이렇게 했는데 혹시 좋은 네이밍 방식이 있을까요??! 추천해주세용

2021-08-12 11:46 UTC, hwookim commented on server/src/routers/wish.router.ts
> +wishRouter.post('/', wrapAsync(wishController.insertItemToWish));
wish를 생성하는 것에 초점을 맞춘다면
그냥 `wishService(Controller).create` 같은 네이밍도 괜찮을 것 같단 생각도 드는군요.🤔
실제로 wish.items 같은 객체에 item을 추가하는 것이 아닌 item을 들고 있는 wish를 생성하는 것이기도 하구요 ㅎㅎ
단순 create보단 좀 더 명확해도 좋을 거 같기도...😅

네이밍... 언제나 너무 어려운 것 같습니다..😢

2021-08-12 11:51 UTC, eun-seong commented on server/src/routers/wish.router.ts
> +wishRouter.post('/', wrapAsync(wishController.insertItemToWish));
오오 sql만 생각하고 삽입 키워드만 생각하고 있었는데 위시 생성이 좋네요!!
`createWish` 로 하겠습니다! 감사합니당~~

2021-08-12 11:57 UTC, eun-seong commented on server/src/services/wish.service.ts
> +      wish ??
0이 falsy한 값이라서 구분하기 위해 이 연산자를 많이 사용하게 되더라구요!

2021-08-12 12:24 UTC, hwookim commented on server/src/controllers/wish.controller.ts
> +  }
PR에 써주신 부분 읽고 고민하고 올린다는걸 밥먹고 오면서 그냥 빼놓고 올렸었군요..! 😅

이 부분은 정책적으로 고민해야하는 부분인 것 같아요.

존재하는 찜하기를 또 등록한 것을 오류로 볼 것인지,
아니면 정당한 요청으로 볼것인지부터 시작할 수 있겠네요.
전자는 409같은 에러를 내보낼 수 있겠고 후자는 현 상태를 유지할 수 있을 것 같습니다.
개인적으로는 정당한 요청의 범주인 것 같아 지금 상태도 좋네요. 😄

다만 오류가 아닌 상황에서 데이터만이 아닌 메시지를 보내는 것이 서버의 역할인지는 저는 조금 고민의 여지가 있는 것 같습니다.
클라이언트는 메시지에 따라서 작업을 해야할까요?
그렇다면 메시지를 클라이언트에서도 관리해야하고, 같은 메시지의 관리 포인트가 두곳이 될 것 같아요.
그보단 `isExisted`의 값을 data의 일부로 응답하고 이에 따라 클라이언트가 처리하는 게 더 낫지 않을까도 싶습니다.

물론 이번의 경우에는 `isExisted`와 무관하게 클라이언트의 행위가 찜목록으로 리다이렉트하는 동일함을 보이긴 하지만요 😅


아예 비즈니스 로직을
`이미 찜한 상품을 다시 찜할 경우 기존 찜하기 삭제`
같은 걸로 변경하는 것도 전 좋은 거 같아요.
게시글의 좋아요같은 기능처럼요.

--- 

생성이 성공한 경우의 status code는 [201](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/201)이 더 어울리는 것 같아요!

2021-08-12 12:49 UTC, eun-seong commented on server/src/controllers/wish.controller.ts
> +  }
말씀해주신 내용에 따라서 클라이언트에서 대응할 수 있게 `isExisted`를 `isWishCreated`로 변경하겠습니다.

저도 비즈니스 로직이 말씀하신 `게시글의 좋아요` 기능처럼 진행했으면 좋겠다는 생각을 하고 있었습니다!
로직을 이렇게 변경한다면 현재 create에서 `isWishCreated`는 남겨놓고
delete에서도 `isWishDeleted` 를 추가하는 게 좋겠군요!

* * *
status code는 생성될 경우에만 201로 변경하겠습니다 :D

2021-08-12 13:00 UTC, SecretJuJu commented on server/src/controllers/wish.controller.ts
> +  }
서버에서 메시지를 직접 전달하지않고 클라이언트에서 보내준 응답에 대한 정해진 응답을 보여주면 어떤까요?

2021-08-12 13:32 UTC, chaeeun037 approved these changes
고생하셨습니다 ><!! 깔꼼하군요

2021-08-12 18:16 UTC, eun-seong commented on server/src/controllers/wish.controller.ts
> +  }
@chaeeun037 @SecretJuJu @hwookim 

wish를 토글하는 방식으로 API 변경하였씁니다~! [확인해주세요 🤓](https://github.com/woowa-techcamp-2021/store-3/pull/24/commits/65a3b3408c2d087bf09a6af09c0335f1f071aa4b)

2021-08-13 06:11 UTC, momongss commented on server/src/controllers/wish.controller.ts
>  interface IGetWishRequest extends Request {
interface 라는 의미로 네임앞에 I 를 붙여두신 것 같네요. 좋아보입니다. 👍

2021-08-13 06:19 UTC, Choi-Jinwoo commented on server/src/controllers/wish.controller.ts
> +    const result = await sequelize.transaction((transaction) => wishService.toggle(transaction, user_id, item_id));
트랜잭션 처리가 service 바깥쪽에 있는 이유는 service 레이어엔 비즈니스 로직만 집중하기 위해서인거죠? 🤔

2021-08-13 08:36 UTC, hwookim approved these changes

2021-08-13 08:37 UTC, SecretJuJu approved these changes
고생하셨습니다 :)

2021-08-13 08:39 UTC, merged