[feature/#13 login api] auth API 전체 개발
woowa-techcamp-2021/store-3 pull request #32
Opened 2021-08-12 12:59 UTC by chaeeun037

## :bookmark_tabs: #0 제목

## :heavy_check_mark: 셀프 체크리스트
> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message가 발생하지 않았나요?
- [ ] Coding Convention을 준수했나요?
- [ ] `npm run lint`나 `yarn lint`를 실행하였나요?

## 소요 시간
> 이슈를 해결하며 사용된 시간

- 8시간

## :speech_balloon: 작업 내용
> 구현 내용 및 작업 했던 내역

### [구현 기능]
- 자체 회원가입 및 소셜 회원가입
- 로그인
- 로그아웃
- 로그인 여부 체크
- 회원 정보 조회
- 회원 정보 수정

### [작업 리스트]
* bcrypt, cookie-parser 모듈 추가
* env 설정 추가 (env.sample 업데이트)
* base error class 추가
* 에러 미들웨어 개발
* auth error class 추가
* 인증 미들웨어 개발
* cookie parser 및 body parser 추가
* auth request interface 추가
* auth service 개발
* auth middleware 개발
* auth controller 개발
* auth router 추가

## :construction: PR 특이 사항
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 자체 로그인한 사용자의 소셜 계정 추가 기능은 명세가 되어 있지 않아서 함께 논의한 후에 개발하겠습니다.

2021-08-12 13:09 UTC, chaeeun037 commented on server/src/services/auth.service.ts
> +      const hashedPassword = await bcrypt.hash(password, parseInt(env.BCRYPT_SALT_ROUNDS));
좋습니당 :) 넘 길쭉하게 적긴 했네용ㅋㅋㅋㅋ

2021-08-12 15:40 UTC, eun-seong reviewed
너무 고생하셨습니다 😆

2021-08-12 15:40 UTC, eun-seong commented on server/src/services/auth.service.ts
> +      const hashedPassword = await bcrypt.hash(password, parseInt(env.BCRYPT_SALT_ROUNDS));
bcrypt 공식 문서에서 [hasing의 sync 버전은 event loop를 block할 수 있기 때문에](https://github.com/kelektiv/node.bcrypt.js#why-is-async-mode-recommended-over-sync-mode) async 버전을 추천하고 있습니다!
그리고 `hash` 메소드에서 salt를 자동으로 생성하기 때문에 저는 분리하지 않아도 나쁘지 않을 것 같습니다 ☺️

2021-08-12 15:40 UTC, eun-seong commented on server/src/services/auth.service.ts
> +    if (user.password === undefined || !bcrypt.compareSync(password, user.password)) {
위 코멘트와 비슷하게 [`compare` 메소드도 async 버전으로](https://github.com/kelektiv/node.bcrypt.js#to-check-a-password) 변경하면 좋을 것 같아요!

2021-08-12 15:40 UTC, eun-seong commented on server/src/controllers/auth.controller.ts
> +    const user = await authService.getLoginUser(body);
`getLoginUser()`의 매개변수로 body 자체를 보내지 않고 `{ login_id, password }`를 꺼내서 직접 전달해주는 건 어떨까요??

2021-08-12 15:40 UTC, eun-seong commented on server/src/controllers/auth.controller.ts
>      const url = `${env.OAUTH_GITHUB_AUTH_URL}`;
ㅋㅋㅋ바뀐 부분은 아닌데 template literal이 의미가 없네요

2021-08-12 15:40 UTC, eun-seong commented on server/src/controllers/auth.controller.ts
> +    res.status(200).json();
회의한 내용에 따라서 code를 204로 변경하면 될 것같습니당

2021-08-12 15:40 UTC, eun-seong commented on server/src/services/auth.service.ts
> +  public async generateJWT(user: User) {
토큰의 paylowd에 유저의 password와 created_at, updated_at, phone 등등 너무 많은 정보가 들어있는게 아닌가 싶은 생각이 드는데 어떻게 생각하시나요?
user 대신에 `id` 혹은 `login_id` 만 들어가도 충분할 것 같습니다. 토큰이 만료되어도 decoding(토큰이 탈취당할 경우 등 대비?)은 가능하니까 최대한 정보를 줄이는 게 어떨까요??

2021-08-12 16:20 UTC, chaeeun037 commented on server/src/controllers/auth.controller.ts
>      const url = `${env.OAUTH_GITHUB_AUTH_URL}`;
그렇네요 ㅋㅋㅋㅋ뭔가 url 합성하다가 이것만 남게된거같은 느낌이네요

2021-08-12 16:20 UTC, chaeeun037 commented on server/src/controllers/auth.controller.ts
> +    res.status(200).json();
넵 ㅎㅎ

2021-08-12 16:20 UTC, chaeeun037 commented on server/src/services/auth.service.ts
> +    if (user.password === undefined || !bcrypt.compareSync(password, user.password)) {
넵 ! 좋은 의견 감사합니당 ㅎㅎ

2021-08-12 16:20 UTC, chaeeun037 commented on server/src/services/auth.service.ts
> +  public async generateJWT(user: User) {
좋습니다 :) 사실 문제점을 알고도.. auth middleware에서 사용의 편리성으로 이렇게 진행했는데 제안해주신 방법대로 수정해보겠습니다!

2021-08-12 16:20 UTC, chaeeun037 commented on server/src/controllers/auth.controller.ts
> +    const user = await authService.getLoginUser(body);
어짜피 이후에 Validation check 코드 추가해줘야해서 login 뿐만 아니라 다른 메소드들 모두 body에서 꺼내서 인자로 전달하는 쪽으로 바꿀 예정입니다!

2021-08-12 16:53 UTC, hwookim requested changes
고생하셨습니다!
프로젝트의 근간이 될 로그인 기능!!!! 🎉🎉🎉

특히 에러 핸들러가 멋지네요!

좀 더 멋지게 하기 위해서,
error의 선언 방식과 관리 방식에 조금만 변화를 주면 어떨까 합니다!
리뷰로 남겨두었으니 확인 부탁드려요~

이 부분도 리뷰에 남겨두었지만,
null 이나 undefined를 검사할 때 `!value` 의 방식으로 검사하는 편이 더 짧고 많은 경우를 커버할 수 있어서 개인적으로는 좋다고 생각합니다.

2021-08-12 16:53 UTC, hwookim commented on server/src/errors/auth.error.ts
> +}
message를 따로 관리하기보다,
object를 상수처럼 사용해서 status code와 message를 매칭시키는 건 어떠신가요?

2021-08-12 16:53 UTC, hwookim commented on server/src/errors/base.error.ts
> +}
status code도 error 객체에서 같이 관리하면 어떨까요?
하위 에러를 `throw new SomeError()` 만 하면 status code와 message가 지정된 걸로 쓸 수 있도록 해도 좋을 것 같아요.☺️

2021-08-12 16:53 UTC, hwookim commented on server/src/middlewares/auth.middleware.ts
> +  if (authorization === null || authorization === undefined) {
```suggestion
  if (!authorization) {
```
한번에 표현할 수 있을 것 같아요! ☺️

2021-08-12 16:53 UTC, hwookim commented on server/src/controllers/auth.controller.ts
> +  }
API의 결과에 의한 이동은 클라이언트의 몫이진 않을까요?
github api를 사용하는 특수한 경우가 아니라면 말이에요 ☺️

2021-08-12 16:53 UTC, hwookim commented on server/src/middlewares/error.middleware.ts
> +  next();
`res.json()`를 한 뒤라면 `next`를 호출할 필요는 없을 것 같아요.

2021-08-12 16:53 UTC, hwookim commented on server/src/middlewares/auth.middleware.ts
> +    req.user = user;
user 전체를 넘기기보단 user.id만 body를 통해 넘기는 건 어떨까요?

```typescript
export interface IAuthRequest extends Request {
  body: {
    user_id: number;
  };
}
```
interface도 이런 식으로 바꿔서 말예요.
이렇게 된다면 `user_id`가 필요한 다른 request에서도 바로 `IAuthRequest`를 상속받아서 작업할 수 있을 거 같아요.
`const userAddress = req.body` 같은 식으로 작성하면서 `userAddress.user_id` 같이 접근할 수 있어서 접근성도 좋아지구요 ☺️
service에 req.body를 통째로 넘길 수도 있을 것 같습니다.

유저의 정보가 생각보다 많아서, 전체를 이동하는 것보다 조금이나마 효율적이지 않을까 합니당!

2021-08-13 00:34 UTC, hwookim approved these changes

2021-08-13 01:09 UTC, chaeeun037 commented on server/src/errors/base.error.ts
> +}
status code 에러 분기처리하는 곳에서 한번에 모아서 관리하는게 더 편하지 않을까요? message도 지정해놓기엔 에러 클래스가 너무 많아질것 같기도 하네요.

2021-08-13 01:09 UTC, chaeeun037 commented on server/src/middlewares/auth.middleware.ts
> +  if (authorization === null || authorization === undefined) {
저는 명시해주는걸 선호하는 편입니다 ㅎㅎ

2021-08-13 01:09 UTC, chaeeun037 commented on server/src/middlewares/auth.middleware.ts
> +    req.user = user;
api 요청에 대한 데이터와 분리시키기 위해 body안에 넣지 않았습니다! 은성님이 피드백해주신것과 같이 user id만 보내는 쪽으로 수정할 예정입니다.

2021-08-13 01:09 UTC, chaeeun037 commented on server/src/middlewares/error.middleware.ts
> +  next();
error middleware인데 next 안해줘도 되나요..?

2021-08-13 01:14 UTC, eun-seong approved these changes
고생하셨씁니다 👍 👍 👍

2021-08-13 01:18 UTC, SecretJuJu commented on server/src/middlewares/error.middleware.ts
> +  }
errors 에서 index 로 한번에 배열로 export 해준뒤 find 로 필요한에러를 찾으면 어떤가요?

2021-08-13 01:20 UTC, SecretJuJu approved these changes
고생하셨습니다! :)
코드가 체계적으로 잘 짜여진것같네요 👍

2021-08-13 01:27 UTC, hwookim commented on server/src/controllers/auth.controller.ts
> +    }
그렇다면 `undefined`일 경우와 `null`일 경우를 모두 체크해주어야할 것 같습니당

2021-08-13 05:18 UTC, juyoungpark718 approved these changes

2021-08-13 05:18 UTC, juyoungpark718 commented on server/src/controllers/auth.controller.ts
> +    }
아니면 isNone 같은 undefined, null을 체크해줄 수 있는 util함수를 만들어서 사용해도 좋아보이는데 어떻게 생각하세요?

2021-08-14 00:42 UTC, merged