[feature/#44 request validate error] request validate error 개발 및 샘플 코드 작성
woowa-techcamp-2021/store-3 pull request #45
Opened 2021-08-15 15:16 UTC by chaeeun037

## :bookmark_tabs: #44  request validate error 개발 및 샘플 코드 작성
resolve #44 

## :heavy_check_mark: 셀프 체크리스트
> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message가 발생하지 않았나요?
- [ ] Coding Convention을 준수했나요?
- [ ] `npm run lint`나 `yarn lint`를 실행하였나요?

## 소요 시간
> 이슈를 해결하며 사용된 시간

- 3시간

## :speech_balloon: 작업 내용
> 구현 내용 및 작업 했던 내역

* 기존의 message에 request validate error를 key, value 형태로 build하여 동적 생성했습니다.

**[작업 내용]**
* `request.error` 추가
* `base.request` 추가
* request validate error에 대한 샘플 코드 작성
  * `test` 도메인을 추가했습니다. request validate 작성하실 때 참고하시면 될 것 같습니다.  
  * 다른 test api가 필요할 때도 활용할 수 있습니다.
  * 추후에 배포할 때에도 해당 코드 삭제가 아닌 router에서 제외하는 방식으로 진행합니다.
    * `test-error.request` 추가
    * test controller 추가
    * test router 추가

## :construction: PR 특이 사항
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 다음 두 스크린샷은 test error api를 활용한 결과입니다. request body와 response에 주목해주세요!

**[request validate 에러 발생 예시]**
<img width="1333" alt="스크린샷 2021-08-15 오후 11 29 55" src="https://user-images.githubusercontent.com/40158029/129483170-f4c0b0fb-6168-4f24-ad90-7ca12f4cd4d2.png">

**[request validate 정상 동작 예시]**
<img width="1355" alt="스크린샷 2021-08-15 오후 11 47 25" src="https://user-images.githubusercontent.com/40158029/129483229-2ea8afae-480b-4716-acb8-39dd8456d77b.png">

- message 형식은 예시로 지정해놓은 것입니다.

2021-08-16 08:48 UTC, hwookim requested changes
한가지 리뷰 달아놓았으니 확인해주시면 감사하겠습니당 ☺️

추가적으로,
저는 `class-validator`를 통한 데이터 추출이 `request`에 한정되는 것이 아니고,
모든 클래스에 대해 진행할 수 있는 것이기 때문에 utils 함수로 분리했었는데요.
사실 지금 당장 request외에는 검증할 클래스가 없기도 해서, 이 부분은 약간 애매모호한 것 같네요. 😅
다른 분들은 어떻게 생각하시는지 궁금합니당 👀

2021-08-16 08:48 UTC, hwookim commented on server/src/errors/request.error.ts
> +  }
현재의 에러 메시지 생성 방식은 에러에 대한 정확한 정보를 제공해주지 않는 것 같아요 👀

대표적으로 `@IsIn(["hi"])`과 같은 validate가 적용되었을 때, 에러는 다음과 같이 뜹니다.
```json
{
  "code": 10001,
  "message": "error: isIn,isNotEmpty"
}
```
`IsIn`에 의해 발생하긴 했지만, 어떤 값을 넣어줘야할지 제대로 알기 힘들다는 점이 있죠.

제가 info 맴버변수를 분리해 작업한 이유는, 여러 변수에 대한 여러 에러를 좀 더 가독성있게 볼 수 있도록 하기 위해서였습니다.
현재의 코드에서 `TestRequest`에 `num`이라는 변수가 추가되고 에러가 발생한다면 메시지는 
`"message": "error: isIn,isNotEmpty\nnum: isInt,isNotEmpty"`
이런 식으로 오게 되더군요.
`\n`로 분리하면 `console.log`에 `error.message`를 따로 찍지 않는 한 구분이 조금 힘들어지는 것도 있네요. 😅

이런 점에서 저는 message와 info를 분리해 관리하는 편을 택했는데,
채은님 생각은 어떠신지 궁금합니다!

2021-08-16 09:26 UTC, hwookim commented on server/src/errors/request.error.ts
> +  }
한 `Error`에서 하나의 `ErrorType`만 존재한다면 생성 시 인자를 `ErrorType`으로 받는 건 조금 불필요한 공정이지 않나 싶기도 합니다.
`RequestError`같은 경우엔 status, code, message 모두 지정되어있고 `info`만 추가적으로 주입하는 상황이기도 하구요.

뒤로는 `info`와는 좀 벗어난, `Error-ErrorType`에 대한 이야기긴 합니다만, 😅 

이것저것 작업 하며 만져보다보니,
`ErrorType`의 존재의의가 무엇인가? 라는 의문도 약간 들더라구요.
`status, code, message`를 담고는 있지만, 이를 통해 어떤 역할도 수행하지 못해 불필요한 은닉, 계층화는 아닐까 싶기도 합니다.
실제로 `Error`에서 `status, code, message`를 꺼낼 때 `error.status`로 진행하며 은닉의 효과도 없게 되구요. 😢

저번에 슬랙에서 잠시 이야기한 것처럼, 두 클래스를 하나로 합치는 것에 대한 생각은 어떠신가요? 👀 
`throw new AuthError(AuthErrorType.TOKEN_EXPIRED);` 가 `throw AuthError.TOKEN_EXPIRED;`로 바뀌는 식으로요.
에러가 static으로 선언되니 동일한 에러가 발생할 때마다 새로 생성하지 않는다는 이점도 겸사겸사 얻을 수 있겠군요.

2021-08-16 10:06 UTC, chaeeun037 commented on server/src/errors/request.error.ts
> +  }
일단 이 PR은 Reuqest error에 관련된 PR이기 때문에, 앞에 말씀하신 부분에 대해서는 현우님이 말씀하신대로 추가적인 인자만 주입하는 방식으로 진행하면 될것 같습니다.

그리고 뒤에 말씀하신 Error-ErrorType 부분은 현우님이 따로 이슈 생성해서 진행하면 될것같습니다.
저는 애초에 error handler 구조 설계를 할 때, 동적인 error와 정적인 error type을 Enum으로 분리하게 되면서(이후에 typescript의 문제로 인해 class로 변경) 이러한 구조가 된것이라 더이상 이견이 없습니다.

하지만 현우님이 더욱 개선하고 싶은 여지가 있다면 언급하신 개선 내용을 이슈 등록하셔서 진행하시고 PR 보내주시면 될 것 같습니다.

2021-08-16 10:32 UTC, eun-seong approved these changes
고민하신 흔적이 보이는 코드입니다👍 👍 👍  수고하셨습니다!!

2021-08-16 12:10 UTC, hwookim commented on server/src/errors/request.error.ts
> +  }
넵, 물론 다른 이슈를 통해 진행해야 한다고 생각하고,
그에 대한 의견을 여쭌 겁니다. ☺️

제시했던 의견 중 Error 자체를 static으로 관리하는 것은 다시 생각해보니 문제가 될 수도 있을 것 같네요.
물론 지금은 error call stack같은 걸 제공하진 않지만, '에러'라는 특성상 정적인 에러는 좀 이상할 수 있겠어요 🤔

어쨋거나 주된 의견은
Error에서 ErrorType을 거치지 않고 직접 status, code, message를 관리하는 것입니다.
불필요한 계층화를 줄이자는 측면에서요 😄

2021-08-17 00:48 UTC, hwookim approved these changes

2021-08-17 02:50 UTC, chaeeun037 commented
request validate 관련해서는 #47 를 채택하게되어 해당 PR을 닫습니다!

2021-08-17 02:50 UTC, closed without merging