user, user_address 모델 정의
woowa-techcamp-2021/store-3 pull request #5
Opened 2021-08-10 17:18 UTC by SecretJuJu

## :bookmark_tabs: #4 user, user_address 모델 정의

## :heavy_check_mark: 셀프 체크리스트
> 최소 3명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] sequelize 환경설정을 했나요?
- [ ] sequelize-typescript 를 이용하여 user 모델을 구성하였나요?
- [ ] user 모델에 빠진것은 없었나요?
- [ ] user_address 모델 또한 위와같나요?

## 소요 시간
> 이슈를 해결하며 사용된 시간

- 3시간

## :speech_balloon: 작업 내용
> 구현 내용 및 작업 했던 내역

* sequelize 버전에 따른 에러 downgrade로 해결 ( sequelize 6.6.5 -> 6.6.2 )
* sequelize 커넥션 설정
* user 모델 설정
* user_address 모델 설정

## :construction: PR 특이 사항
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 모델을 정의하는 방법 및 고칠점

(작업 내역 확인하기 편하도록 이미지 첨부)

2021-08-10 17:20 UTC, SecretJuJu commented on server/src/models/index.ts
> +  //   logging: false,
이 부분은 default가 true인데 true일 경우 sequelize가 사용한 쿼리가 출력됩니다.
모델부분을 개발할때에는 이 logging부분을 true로 하고 개발하는것을 추천합니다!

2021-08-11 00:46 UTC, hwookim requested changes
새벽까지 고생하셨습니다!
몇가지 리뷰 남기고, 작업하며 수정하겠습니다.
한 번 확인 부탁드려요 ㅎㅎ

2021-08-11 00:46 UTC, hwookim commented on server/src/models/index.ts
> +};
.env로 빼두면 좋을 것 같군요! ☺️

2021-08-11 00:46 UTC, hwookim commented on server/src/models/user.model.ts
> +  login_id!: string;
확장적 할당 단언을 이용하신 이유가 있을까요?
이는 해당 `undefind`여도 문제가 없을 거라는 선언이 되는데,
`AllowNull(false)`를 해둔 상황과 논리적으로 오류이지 않나 싶습니다 🤔

혹시 따로 선언하신 이유가 있다면 알려주세요 ☺️

2021-08-11 00:46 UTC, hwookim commented on server/src/models/user.model.ts
> +  updatedAt: 'updated_at',
`underscore: true`
옵션을 사용한다면 하나하나 명시하지 않으셔도 의도하신 대로 컬럼이 생성됩니다!
아래의 맴버변수들을 camelCase로 선언해도 자동으로 치환됩니당 😁

2021-08-11 00:55 UTC, hwookim commented on server/src/models/index.ts
> +export default syncSequelize;
후에 `sequelize.transaction` 등을 선언 할 때 여기서 생성된 `sequlize` 객체가 필요해지진 않을까요?

현재 상태는 `authenticate`를 통해 DB connection을 테스트한 뒤 테스트가 실패할 경우에 대응이 없고,
내부에서 try-catch문을 통해 같은 행위를 반복하는 것으로 보이네요.
`sequelize.sync()`만 try-catch문으로 감싸는 것과 차이가 있을까요?
또한, catch시 error를 console.err로 출력한다면 DB connection에서 오류가 나더라도 노드는 종료되지 않고 계속 실행될 것 같아요.
catch문의 역할을 `express.on('error')`로 넘기는 건 어떨까요?

2021-08-11 01:00 UTC, hwookim commented on server/src/models/user.model.ts
> +  timestamps: true,
`tableName`을 명시해주셨기 때문에 `freezeTableName`은 설정하지 않으셔도 될 것 같아요! 😄
`timestamps`는 default가 `true`이기 때문에 또한 명시하지 않으셔도 괜찮을 것 같습니당

2021-08-11 01:07 UTC, chaeeun037 commented on server/src/models/user.model.ts
> +  login_id!: string;
https://sequelize.org/master/manual/typescript.html

관련 문서입니다!

2021-08-11 01:09 UTC, hwookim commented on server/src/models/user.model.ts
> +  login_id!: string;
https://github.com/woowa-techcamp-2021/cashbook-15/blob/dev/src/models/Record.ts

저는 이전에 이렇게 사용한 경험이 있었는데,
왜 얘는 오류가 안났는지 졸 모르겠네요...🤔

2021-08-11 01:14 UTC, hwookim commented on server/src/models/user.model.ts
> +  default_address: number | undefined;
```suggestion
  provider?: string;

  @HasMany(() => UserAddress)
  user_address?: UserAddress[];

  @AllowNull(true)
  @Column(DataType.INTEGER)
  default_address?: number;
```

이렇게 표현할 수도 있을 거 같아요 😀

2021-08-11 01:17 UTC, hwookim commented on server/src/models/user.model.ts
> +  default_address: number | undefined;
```suggestion
  @AllowNull
  @Column(DataType.STRING(10))
  provider?: string;

  @HasMany(() => UserAddress)
  user_address?: UserAddress[];

  @AllowNull
  @Column(DataType.INTEGER)
  default_address?: number;
```

이렇게도 가능할 것 같네요 😄

2021-08-11 01:22 UTC, SecretJuJu commented on server/src/models/index.ts
> +};
좋습니다! 디렉토리 구조를 잡을때 config 해줄 모듈이 어디올지 몰라서 일단 위처럼 해 놨습니다. :)

2021-08-11 01:24 UTC, chaeeun037 commented on server/src/models/userAddress.model.ts
> +  zip_code!: number;
우편번호는 핸드폰번호처럼 decimal이나 number 타입보다는 string의 성격이 강하다고 생각이 드는데 어떠신가요?

2021-08-11 01:25 UTC, SecretJuJu commented on server/src/models/user.model.ts
> +  default_address: number | undefined;
오 그렇게도 할 수 있군요 좋습니다 👍

2021-08-11 01:26 UTC, chaeeun037 approved these changes

2021-08-11 01:37 UTC, SecretJuJu commented on server/src/models/index.ts
> +export default syncSequelize;
좋습니다!
그러면 sequelize 객체, syncSequelize 들을 따로따로 export 해주면 될까요?

2021-08-11 01:38 UTC, SecretJuJu commented on server/src/models/user.model.ts
> +  timestamps: true,
오 timestamp 와 freezeTableName을 지운뒤에 underscored옵션을 true 해 주니 똑같이 작동하네요 그럼 이렇게 하도록 하겠습니다.

2021-08-11 01:41 UTC, SecretJuJu commented on server/src/models/userAddress.model.ts
> +  zip_code!: number;
https://stackoverflow.com/questions/15843688/what-is-the-best-column-type-for-a-united-states-zip-code
생각해보니 5자리 문자열이 맞을 것 같은데 어떤가요??

2021-08-11 05:08 UTC, hwookim commented on server/src/models/index.ts
> +export default syncSequelize;
뒤의 말씀도 좋다고 하신거라면
별도의 `syncSequelize` 함수가 필요 없이 listen 시 `sequelize.sync()`를 통해 실행하고 `listen().on('error')`로 처리하는 방법도 있습니다.
그렇게 되면 `sequelize` 객체만 export default 해도 괜찮지 않을까요?.

2021-08-11 05:13 UTC, hwookim commented on server/src/models/index.ts
> +};
우선 해당 파일의 상단에 dotenv 설정을 해두고 후에 분리해도 괜찮을 것 같아요.
이 상태라면 승보님의 DB 설정에 맞게 각자의 DB를 수정해야 작업 확인이 가능할 것 같아서요 ㅎㅎ..😅

2021-08-11 05:14 UTC, hwookim commented on server/src/models/index.ts
> +  //   logging: false,
실제 환경에서도 로그 기록을 위해 logging을 끌 일은 없을 것 같은데,
false로 둘 일이 있나요?

2021-08-11 05:41 UTC, eun-seong commented
부가적인 이유이지만 네이밍에 관해서 [sequelize-typescript DOCS](https://github.com/RobinBuschmann/sequelize-typescript#model-path-resolving)에 
> For each file that matches the *.model.ts pattern, the modelMatch function will be called with its exported members.

문구로 기재가 되어 있네요! 파일 네이밍은 정해진 포맷대로 하거나 모델을 `export`를 따로 해주어야 하는 것 같습니다.

2021-08-11 05:42 UTC, eun-seong commented on server/src/models/user.model.ts
> +  login_id!: string;
아무래도 `tsconfig` 문제인 것 같기도 합니다.
`"strictPropertyInitialization": false` 옵션을 주니 해결이 되긴 하네용.. 생성자에서 멤버변수를 초기화하지 않은 것 때문에 그런 것 같습니다.

2021-08-11 05:46 UTC, SecretJuJu commented on server/src/models/index.ts
> +export default syncSequelize;
넵 좋습니다. 그럼 디렉토리 구조에따라 처리할 수 있게 일단 sequelize 객체만 export 하겠습니다!

2021-08-11 06:22 UTC, chaeeun037 commented on server/src/models/userAddress.model.ts
> +  zip_code!: number;
좋습니다! :)

2021-08-11 06:41 UTC, hwookim approved these changes
와 고생하셨습니다!
최고예요!

2021-08-11 06:46 UTC, chaeeun037 commented
최고입니다 !!

2021-08-11 06:46 UTC, merged