[Feature/#77 router improvement] router 개선
woowa-techcamp-2021/store-3 pull request #80
Opened 2021-08-19 12:57 UTC by chaeeun037

## :bookmark_tabs: #77  router 개선
resolve #77 

## :heavy_check_mark: 셀프 체크리스트
> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message가 발생하지 않았나요?
- [ ] Coding Convention을 준수했나요?
- [ ] `npm run lint`나 `yarn lint`를 실행하였나요?

## 소요 시간
> 이슈를 해결하며 사용된 시간

- 4시간

## :speech_balloon: 작업 내용
> 구현 내용 및 작업 했던 내역

* webpack app.js 상대 경로로 인한 404 에러 버그 수정
* router params 동적 path 기능 추가
* router hash 기능 추가

* router query 기능 추가
* router 개선사항 적용한 샘플  page 작성

## :construction: PR 특이 사항
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
![스크린샷 2021-08-19 오후 9 56 20](https://user-images.githubusercontent.com/40158029/130072057-fdd50b2e-40f6-44d9-bcba-6cfe8c5e210d.png)
![스크린샷 2021-08-19 오후 9 56 36](https://user-images.githubusercontent.com/40158029/130072084-197e8309-1e1d-4735-bb86-ac3806d10351.png)
![스크린샷 2021-08-19 오후 9 55 54](https://user-images.githubusercontent.com/40158029/130072008-176fd04c-4f82-4289-a69e-5954be306c49.png)

2021-08-19 14:36 UTC, SecretJuJu approved these changes
이해하기 쉽게 코드를 잘 짜신거같아요! 👍

2021-08-19 14:36 UTC, SecretJuJu commented on client/src/lib/Router/Route.tsx
> +  const regex = new RegExp(`^(${compiledPath})$`, 'i');
오 여기서 :key 키들을 떼주는군요

2021-08-19 14:36 UTC, SecretJuJu commented on client/src/lib/Router/Route.tsx
> +      const params = match.slice(2);
match 에 데이터가 어떤식으로 오나요??

2021-08-19 14:36 UTC, SecretJuJu commented on client/src/lib/Router/Route.tsx
routes가 Array 가 아닐때도 있나요?

2021-08-19 15:12 UTC, hwookim requested changes
정규식 너무 어렵군요..!
진짜 어려운 작업이었을 것 같은데, 깔끔하게 동작하니 멋지네요 🎉  🎉 
정말 고생하셨습니다!!!

라우터 동작 방식에 관해서 리뷰 남긴 것이 있으니 한 번 확인 부탁드려요!

2021-08-19 15:12 UTC, hwookim commented on client/src/lib/Router/Route.tsx
> +  }
```suggestion 
  const router = useRouterContext();
  const { currentPath } = router;

  if (path === currentPath) {
    return React.createElement(component);
  }

  const { regex, keys } = compilePath(path);
  const match = currentPath.match(regex);
  if (match) {
    const params = match.slice(2);
    router.params = keys.reduce<{ [key: string]: string }>((obj, key, i) => {
      obj[key] = params[i];
      return obj;
    }, {});
    return React.createElement(component);
  }
```

전체 route를 순회하지 않아도 각 라우터가 리랜더링되며 내부 함수를 실행합니다.
순회가 사라진다면 이런 식으로도 표현할 수 있을 것 같아요 😄 
`router context`에 `routes`를 넘겨주지 않아도 될 것 같네요.

2021-08-19 15:12 UTC, hwookim commented on client/src/lib/Router/Route.tsx
> +  });
와 정규식 마스터시군요....!!!! 👍🏼 👍🏼 👍🏼

2021-08-19 16:05 UTC, chaeeun037 commented on client/src/lib/Router/Route.tsx
> +  return <></>;
match에 걸리지 않을 때 default return이 있어야 합니다! :)

2021-08-19 16:12 UTC, hwookim approved these changes
👍🏼 👍🏼 
머지 전 프로덕션에 포함된 테스트를 위한 코드들은 사라지려나욤??

2021-08-19 16:12 UTC, hwookim commented on client/webpack.config.dev.js
> +const path = require('path');
이젠 안쓰이는군요!

`npx eslint .`를 한번씩 돌려보는 것도 좋은 것 같아요 ㅎㅎ

2021-08-19 16:12 UTC, hwookim commented on client/src/lib/Router/Route.tsx
> +import { IRouterContext, useRouterContext } from './Router';
수정하시면서 안쓰이게 된 친구들이 있슴당 ☺️

2021-08-19 16:14 UTC, hwookim commented on client/src/lib/Router/Route.tsx
> +  const { path: targetPath } = (route as JSX.Element).props as IRouteProps;
후후 이젠 공통 컴포넌트가 와도 괜찮을 것 같군요! 👍🏼 👍🏼

2021-08-19 17:24 UTC, eun-seong approved these changes
우와 어려워보였는데 정말 깔끔하게 너무 잘 짜셨네요! 
멋져용❣️

2021-08-19 18:57 UTC, chaeeun037 commented on client/webpack.config.dev.js
> +const path = require('path');
아하~ 린트는 까먹고 안돌리고있었네요! 지워버리겠습니다!

2021-08-19 19:06 UTC, chaeeun037 commented on client/src/lib/Router/Route.tsx
> +import { IRouterContext, useRouterContext } from './Router';
넵 삭제해버렸습니다!

2021-08-19 19:07 UTC, chaeeun037 commented
테스트 코드는 샘플로 남겨두려고요~ 없애니까 다시 작성하기가 힘들더라고요 ㅠㅠ
실제 코드 작성하면서 삭제될거같습니다 :)

2021-08-19 19:07 UTC, merged

2021-08-20 05:50 UTC, Seogeurim commented
필요한 부분만 작성해서 깔끔하고 너무 좋네요!! query, params까지 코드 읽으면서 많이 배웠습니다 👍